blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/managing-privately-reported-security-vulnerabilities
    about: Please use GitHub Security Advisories for private vulnerability reports.
